### PR TITLE
Release OIDC Proxy 0.1.0

### PR DESCRIPTION
**Pull request by sberyozkin**

### CODE REVIEW

**Comment by sberyozkin** [comment]
Hey @gastaldi This release failed due to a docs related issue, https://github.com/quarkiverse/quarkus-oidc-proxy/actions/runs/8334141647/job/22807123942, do you know what I need to fix ?

**Comment by gastaldi** [comment]
Yes, it's missing a pom.xml there, have you created this extension using `quarkus create extension oidc-proxy`?  That will generate them for you

**Comment by gastaldi** [comment]
@sberyozkin I'll push a fix for you, hold on

**Comment by gastaldi** [comment]
@sberyozkin see https://github.com/quarkiverse/quarkus-oidc-proxy/pull/3

**Comment by sberyozkin** [comment]
Thanks @gastaldi and sorry about it, I copied one of the old quarkiverse extensions and just replaced some bits there, which was not right

**Pull request merged**
